In [1]:
import pandas as pd
import numpy as np

In [2]:
cb_pred = pd.read_csv("../data/pred13_catboost_bowhash.csv")
lgb_pred = pd.read_csv("../data/pred15_LGBM_bowbin_fi.csv")
nb_pred = pd.read_csv("../data/res_NB_2.csv")
tf_pred = pd.read_csv("../data/res_TF_GloVe.2.csv")

In [3]:
print(cb_pred["target"].mean())
print(lgb_pred["target"].mean())
print(nb_pred["target"].mean())
print(tf_pred["target"].mean())

0.33925835121054243
0.3426294820717131
0.32301562978853815
0.36254980079681276


In [4]:
cb_pred.target.value_counts()

0    2156
1    1107
Name: target, dtype: int64

In [5]:
lgb_pred.target.value_counts()

0    2145
1    1118
Name: target, dtype: int64

In [7]:
y_pred_avg = (cb_pred.target + lgb_pred.target) / 2
y_pred_avg

0       0.5
1       1.0
2       1.0
3       0.0
4       1.0
       ... 
3258    1.0
3259    1.0
3260    1.0
3261    1.0
3262    0.0
Name: target, Length: 3263, dtype: float64

In [9]:
y_pred = np.where(y_pred_avg >= 0.5, 1,0)
y_pred

array([1, 1, 1, ..., 1, 1, 0])

In [6]:
sample_submit = pd.read_csv("../data/sample_submission.csv")
sample_submit.head()

id  target
0   0       0
1   2       0
2   3       0
3   9       0
4  11       0

In [13]:
sample_submit["target"] = y_pred
sample_submit["target"].mean()

0.3873735825927061

In [21]:
sample_submit.to_csv("../data/pred16_ensamble.csv", index=False)

In [6]:
nb_pred.head()

id  target
0   0       1
1   2       0
2   3       1
3   9       1
4  11       1

In [31]:
y_pred_avg = (cb_pred.target + lgb_pred.target + nb_pred.target) / 3
y_pred_avg

0       0.666667
1       0.666667
2       1.000000
3       0.333333
4       1.000000
          ...   
3258    1.000000
3259    1.000000
3260    1.000000
3261    1.000000
3262    0.333333
Name: target, Length: 3263, dtype: float64

In [32]:
y_pred = np.where(y_pred_avg >= 0.5, 1,0)
y_pred

array([1, 1, 1, ..., 1, 1, 0])

In [33]:
sample_submit["target"] = y_pred
sample_submit["target"].mean()

0.3312902237205026

In [34]:
sample_submit.to_csv("../data/pred17_ensamble2.csv", index=False)

In [8]:
y_pred_avg = (cb_pred.target * 0.3) + (lgb_pred.target * 0.2) + (nb_pred.target * 0.5)
y_pred_avg

0       0.8
1       0.5
2       1.0
3       0.5
4       1.0
       ... 
3258    1.0
3259    1.0
3260    1.0
3261    1.0
3262    0.5
Name: target, Length: 3263, dtype: float64

In [9]:
y_pred = np.where(y_pred_avg >= 0.5, 1,0)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [10]:
sample_submit["target"] = y_pred
sample_submit["target"].mean()

0.3637756665645112

In [12]:
sample_submit.to_csv("../data/pred19_ensamble3.csv", index=False)

In [12]:
y_pred_avg = (cb_pred.target * 0.4) + (nb_pred.target * 0.6)
y_pred_avg

0       1.0
1       0.4
2       1.0
3       0.6
4       1.0
       ... 
3258    1.0
3259    1.0
3260    1.0
3261    1.0
3262    0.6
Name: target, Length: 3263, dtype: float64

In [13]:
y_pred = np.where(y_pred_avg >= 0.5, 1,0)
y_pred

array([1, 0, 1, ..., 1, 1, 1])

In [14]:
sample_submit["target"] = y_pred
sample_submit["target"].mean()

0.32301562978853815

In [15]:
sample_submit.to_csv("../data/pred20_ensamble4.csv", index=False)

In [8]:
y_pred_avg = (cb_pred.target * 0.5) + (nb_pred.target * 0.5)
y_pred_avg

0       1.0
1       0.5
2       1.0
3       0.5
4       1.0
       ... 
3258    1.0
3259    1.0
3260    1.0
3261    1.0
3262    0.5
Name: target, Length: 3263, dtype: float64

In [9]:
y_pred = np.where(y_pred_avg >= 0.5, 1,0)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [10]:
sample_submit["target"] = y_pred
sample_submit["target"].mean()

0.3867606497088569

In [11]:
sample_submit.to_csv("../data/pred22_ensamble5.csv", index=False)

In [7]:
y_pred_avg = ((cb_pred.target) + (nb_pred.target) + tf_pred.target ) / 3
y_pred_avg

0       1.000000
1       0.666667
2       1.000000
3       0.666667
4       1.000000
          ...   
3258    1.000000
3259    1.000000
3260    1.000000
3261    1.000000
3262    0.666667
Name: target, Length: 3263, dtype: float64

In [8]:
y_pred = np.where(y_pred_avg >= 0.5, 1,0)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [9]:
sample_submit["target"] = y_pred
sample_submit["target"].mean()

0.3312902237205026

In [10]:
sample_submit.to_csv("../data/pred23_ensamble6.csv", index=False)

In [11]:
y_pred_avg = (cb_pred.target * 0.2) + (nb_pred.target * 0.3) + (tf_pred.target * 0.5)
y_pred_avg

0       1.0
1       0.7
2       1.0
3       0.8
4       1.0
       ... 
3258    1.0
3259    1.0
3260    1.0
3261    1.0
3262    0.8
Name: target, Length: 3263, dtype: float64

In [12]:
y_pred = np.where(y_pred_avg >= 0.5, 1,0)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [13]:
sample_submit["target"] = y_pred
sample_submit["target"].mean()

0.3840024517315354

In [14]:
sample_submit.to_csv("../data/pred24_ensamble7.csv", index=False)

In [19]:
y_pred_avg = (nb_pred.target * 0.5) + (tf_pred.target * 0.5)
y_pred_avg

0       1.0
1       0.5
2       1.0
3       1.0
4       1.0
       ... 
3258    1.0
3259    1.0
3260    1.0
3261    1.0
3262    1.0
Name: target, Length: 3263, dtype: float64

In [20]:
y_pred = np.where(y_pred_avg >= 0.5, 1,0)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [21]:
sample_submit["target"] = y_pred
sample_submit["target"].mean()

0.4082133006435795

In [18]:
sample_submit.to_csv("../data/pred25_ensamble8.csv", index=False)

In [4]:
y_pred_avg = (cb_pred.target * 0.3) + (lgb_pred.target * 0.2) + (tf_pred.target * 0.5)
y_pred = np.where(y_pred_avg >= 0.5, 1,0)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [7]:
sample_submit["target"] = y_pred
sample_submit["target"].mean()

0.39380937787312287

In [8]:
sample_submit.to_csv("../data/pred26_ensamble9.csv", index=False)